---
- name: Run pre-flight assertions
  ansible.builtin.import_tasks: assert.yml
  tags:
    - always

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - always

- name: Run OS-specific SSH hardening tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
  tags:
    - ssh
    - ssh-hardening
